import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ColorfulWebsite from "./colorful";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PDFWatermarkTool",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="favicon.ico" />
      </Head>
      <body>
        <ColorfulWebsite />
      </body>
    </html>
  );
}
// <html lang="en">
//   <body
//     className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-blue-50 via-white to-blue-100 min-h-screen`}
//   >
//     <Navbar />

//     <main className="max-w-4xl mx-auto mt-8 p-6 bg-white/80 rounded-xl shadow-xl border border-blue-100 backdrop-blur-sm">
//       {children}
//     </main>

//     <Footer />
//   </body>
// </html>
